version: '2.2'
services:
  wallet-mongo:
    container_name: wallet-mongo
    image: mongo
    restart: always
    command: --wiredTigerCacheSizeGB 6.0
    volumes:
      - wallet-mongodb-vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier
    mem_limit: 6144m

  wallet-node-api:
    container_name: wallet-node-api
    restart: always
    depends_on:
      - wallet-mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
      - $GLS_METRICS_API_HOST:$GLS_METRICS_API_PORT:$GLS_METRICS_API_PORT
    env_file:
      - .env
    environment:
      - GLS_ENABLE_READ_MODE=true
    mem_limit: 2048m
    cpus: 3

  wallet-node-writer:
    container_name: wallet-node-writer
    restart: always
    depends_on:
      - wallet-mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
      ports:
        - $GLS_CONNECTOR_WRITER_PORT:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_WRITER_PORT
    environment:
      - GLS_ENABLE_WRITE_MODE=true
    env_file:
      - .env
    mem_limit: 2048m
    cpus: 3

volumes:
  wallet-mongodb-vol:

networks:
  services-tier:
